import type { CitySnapshot, FileData, DistrictData, CityStats } from "./types/city"
import { DISTRICT_COLORS } from "./types/city"

// ============================================================
// Demo data: mem0ai/mem0 — AI Memory Layer for LLM applications
// 8 districts, ~35 files, mirrors the real repository structure
// ============================================================

// ---------- districts (4×2 grid) ----------

const districts: DistrictData[] = [
  {
    name: "memory",
    color: DISTRICT_COLORS[0], // cyan — core module
    files: [
      "mem0/memory/main.py",
      "mem0/memory/base.py",
      "mem0/memory/telemetry.py",
      "mem0/memory/utils.py",
      "mem0/memory/setup.py",
    ],
    bounds: { x: -9, z: -6, width: 5.5, depth: 3.5 },
  },
  {
    name: "llms",
    color: DISTRICT_COLORS[1], // green — LLM providers
    files: [
      "mem0/llms/openai.py",
      "mem0/llms/anthropic.py",
      "mem0/llms/azure_openai.py",
      "mem0/llms/base.py",
      "mem0/llms/configs.py",
    ],
    bounds: { x: -3, z: -6, width: 5.5, depth: 3.5 },
  },
  {
    name: "embeddings",
    color: DISTRICT_COLORS[2], // blue — embedding providers
    files: [
      "mem0/embeddings/openai.py",
      "mem0/embeddings/huggingface.py",
      "mem0/embeddings/base.py",
      "mem0/embeddings/configs.py",
    ],
    bounds: { x: 3, z: -6, width: 5.5, depth: 3.5 },
  },
  {
    name: "vector_stores",
    color: DISTRICT_COLORS[4], // purple — vector databases
    files: [
      "mem0/vector_stores/qdrant.py",
      "mem0/vector_stores/chroma.py",
      "mem0/vector_stores/base.py",
      "mem0/vector_stores/configs.py",
    ],
    bounds: { x: 9, z: -6, width: 5.5, depth: 3.5 },
  },
  {
    name: "graphs",
    color: DISTRICT_COLORS[5], // orange — knowledge graphs
    files: [
      "mem0/graphs/tools.py",
      "mem0/graphs/utils.py",
      "mem0/graphs/base.py",
    ],
    bounds: { x: -9, z: -1.5, width: 5.5, depth: 3.5 },
  },
  {
    name: "client",
    color: DISTRICT_COLORS[7], // teal — SDK client
    files: [
      "mem0/client/main.py",
      "mem0/client/models.py",
      "mem0/client/api.py",
    ],
    bounds: { x: -3, z: -1.5, width: 5.5, depth: 3.5 },
  },
  {
    name: "configs",
    color: DISTRICT_COLORS[3], // yellow — configuration
    files: [
      "mem0/configs/base.py",
      "mem0/configs/prompts.py",
      "mem0/configs/defaults.py",
    ],
    bounds: { x: 3, z: -1.5, width: 5.5, depth: 3.5 },
  },
  {
    name: "utils",
    color: DISTRICT_COLORS[6], // pink — shared utilities
    files: [
      "mem0/utils/factory.py",
      "mem0/utils/logger.py",
      "mem0/utils/helpers.py",
    ],
    bounds: { x: 9, z: -1.5, width: 5.5, depth: 3.5 },
  },
]

// ---------- files ----------

const filesRaw: Omit<FileData, "externalImports" | "decorators" | "fileType">[] = [
  // ── memory district (core hub — high complexity) ──
  {
    path: "mem0/memory/main.py",
    lines: 620,
    functions: [
      { name: "Memory", exported: true, lines: 180 },
      { name: "add", exported: true, lines: 85 },
      { name: "search", exported: true, lines: 70 },
      { name: "update", exported: true, lines: 55 },
      { name: "delete", exported: true, lines: 30 },
      { name: "get_all", exported: true, lines: 40 },
      { name: "history", exported: true, lines: 35 },
      { name: "_parse_messages", exported: false, lines: 45 },
    ],
    types: [
      { name: "MemoryConfig", kind: "class" },
      { name: "SearchResult", kind: "class" },
    ],
    classes: [{ name: "Memory" }],
    imports: [
      "mem0/memory/base.py",
      "mem0/memory/utils.py",
      "mem0/memory/telemetry.py",
      "mem0/llms/base.py",
      "mem0/embeddings/base.py",
      "mem0/vector_stores/base.py",
      "mem0/configs/base.py",
      "mem0/utils/factory.py",
    ],
    importedBy: ["mem0/client/main.py", "mem0/memory/setup.py"],
    complexity: 32,
    isReactComponent: false,
    hasUnusedExports: false,
    position: { x: -8.2, z: -5.2 },
    district: "memory",
  },
  {
    path: "mem0/memory/base.py",
    lines: 280,
    functions: [
      { name: "MemoryBase", exported: true, lines: 120 },
      { name: "_add_to_vector_store", exported: false, lines: 50 },
      { name: "_add_to_graph", exported: false, lines: 40 },
      { name: "_search_vector_store", exported: false, lines: 35 },
    ],
    types: [
      { name: "MemoryBase", kind: "class" },
      { name: "MemoryItem", kind: "class" },
    ],
    classes: [{ name: "MemoryBase" }],
    imports: [
      "mem0/configs/base.py",
      "mem0/utils/logger.py",
    ],
    importedBy: ["mem0/memory/main.py"],
    complexity: 24,
    isReactComponent: false,
    hasUnusedExports: false,
    position: { x: -6.4, z: -5.2 },
    district: "memory",
  },
  {
    path: "mem0/memory/telemetry.py",
    lines: 160,
    functions: [
      { name: "capture_event", exported: true, lines: 40 },
      { name: "init_telemetry", exported: true, lines: 30 },
      { name: "track_api_call", exported: true, lines: 25 },
      { name: "_get_anonymous_id", exported: false, lines: 20 },
    ],
    types: [{ name: "TelemetryEvent", kind: "class" }],
    classes: [{ name: "TelemetryClient" }],
    imports: ["mem0/utils/logger.py"],
    importedBy: ["mem0/memory/main.py"],
    complexity: 12,
    isReactComponent: false,
    hasUnusedExports: false,
    position: { x: -8.2, z: -3.4 },
    district: "memory",
  },
  {
    path: "mem0/memory/utils.py",
    lines: 190,
    functions: [
      { name: "parse_messages", exported: true, lines: 55 },
      { name: "format_memories", exported: true, lines: 35 },
      { name: "get_fact_retrieval_messages", exported: true, lines: 40 },
      { name: "remove_code_blocks", exported: true, lines: 15 },
      { name: "clean_response", exported: false, lines: 20 },
    ],
    types: [],
    classes: [],
    imports: ["mem0/configs/prompts.py"],
    importedBy: ["mem0/memory/main.py", "mem0/graphs/utils.py"],
    complexity: 14,
    isReactComponent: false,
    hasUnusedExports: true,
    position: { x: -6.4, z: -3.4 },
    district: "memory",
  },
  {
    path: "mem0/memory/setup.py",
    lines: 80,
    functions: [
      { name: "setup", exported: true, lines: 35 },
      { name: "validate_config", exported: true, lines: 25 },
    ],
    types: [],
    classes: [],
    imports: ["mem0/memory/main.py", "mem0/configs/defaults.py"],
    importedBy: [],
    complexity: 6,
    isReactComponent: false,
    hasUnusedExports: false,
    position: { x: -4.6, z: -5.2 },
    district: "memory",
  },

  // ── llms district (provider adapters) ──
  {
    path: "mem0/llms/openai.py",
    lines: 220,
    functions: [
      { name: "OpenAILLM", exported: true, lines: 60 },
      { name: "generate_response", exported: true, lines: 50 },
      { name: "_prepare_messages", exported: false, lines: 35 },
      { name: "_handle_streaming", exported: false, lines: 40 },
    ],
    types: [{ name: "OpenAIConfig", kind: "class" }],
    classes: [{ name: "OpenAILLM" }],
    imports: ["mem0/llms/base.py", "mem0/llms/configs.py", "mem0/utils/logger.py"],
    importedBy: ["mem0/utils/factory.py"],
    complexity: 18,
    isReactComponent: false,
    hasUnusedExports: false,
    position: { x: -2.2, z: -5.2 },
    district: "llms",
  },
  {
    path: "mem0/llms/anthropic.py",
    lines: 195,
    functions: [
      { name: "AnthropicLLM", exported: true, lines: 55 },
      { name: "generate_response", exported: true, lines: 45 },
      { name: "_format_messages", exported: false, lines: 30 },
      { name: "_handle_tool_use", exported: false, lines: 35 },
    ],
    types: [{ name: "AnthropicConfig", kind: "class" }],
    classes: [{ name: "AnthropicLLM" }],
    imports: ["mem0/llms/base.py", "mem0/llms/configs.py", "mem0/utils/logger.py"],
    importedBy: ["mem0/utils/factory.py"],
    complexity: 16,
    isReactComponent: false,
    hasUnusedExports: false,
    position: { x: -0.4, z: -5.2 },
    district: "llms",
  },
  {
    path: "mem0/llms/azure_openai.py",
    lines: 170,
    functions: [
      { name: "AzureOpenAILLM", exported: true, lines: 50 },
      { name: "generate_response", exported: true, lines: 40 },
      { name: "_get_deployment", exported: false, lines: 25 },
    ],
    types: [{ name: "AzureConfig", kind: "class" }],
    classes: [{ name: "AzureOpenAILLM" }],
    imports: ["mem0/llms/base.py", "mem0/llms/configs.py"],
    importedBy: ["mem0/utils/factory.py"],
    complexity: 13,
    isReactComponent: false,
    hasUnusedExports: false,
    position: { x: 1.4, z: -5.2 },
    district: "llms",
  },
  {
    path: "mem0/llms/base.py",
    lines: 130,
    functions: [
      { name: "BaseLLM", exported: true, lines: 40 },
      { name: "generate_response", exported: true, lines: 25 },
      { name: "validate_config", exported: true, lines: 20 },
    ],
    types: [
      { name: "LLMResponse", kind: "class" },
      { name: "BaseLLM", kind: "class" },
    ],
    classes: [{ name: "BaseLLM" }],
    imports: ["mem0/configs/base.py"],
    importedBy: [
      "mem0/llms/openai.py",
      "mem0/llms/anthropic.py",
      "mem0/llms/azure_openai.py",
      "mem0/memory/main.py",
      "mem0/graphs/base.py",
    ],
    complexity: 8,
    isReactComponent: false,
    hasUnusedExports: false,
    position: { x: -2.2, z: -3.4 },
    district: "llms",
  },
  {
    path: "mem0/llms/configs.py",
    lines: 85,
    functions: [
      { name: "LLMConfig", exported: true, lines: 30 },
      { name: "get_default_config", exported: true, lines: 20 },
    ],
    types: [
      { name: "LLMConfig", kind: "class" },
      { name: "ProviderType", kind: "enum" },
    ],
    classes: [{ name: "LLMConfig" }],
    imports: ["mem0/configs/base.py"],
    importedBy: [
      "mem0/llms/openai.py",
      "mem0/llms/anthropic.py",
      "mem0/llms/azure_openai.py",
    ],
    complexity: 4,
    isReactComponent: false,
    hasUnusedExports: false,
    position: { x: -0.4, z: -3.4 },
    district: "llms",
  },

  // ── embeddings district ──
  {
    path: "mem0/embeddings/openai.py",
    lines: 150,
    functions: [
      { name: "OpenAIEmbedding", exported: true, lines: 45 },
      { name: "embed", exported: true, lines: 30 },
      { name: "_batch_embed", exported: false, lines: 35 },
    ],
    types: [{ name: "OpenAIEmbeddingConfig", kind: "class" }],
    classes: [{ name: "OpenAIEmbedding" }],
    imports: ["mem0/embeddings/base.py", "mem0/embeddings/configs.py", "mem0/utils/logger.py"],
    importedBy: ["mem0/utils/factory.py"],
    complexity: 11,
    isReactComponent: false,
    hasUnusedExports: false,
    position: { x: 3.8, z: -5.2 },
    district: "embeddings",
  },
  {
    path: "mem0/embeddings/huggingface.py",
    lines: 130,
    functions: [
      { name: "HuggingFaceEmbedding", exported: true, lines: 40 },
      { name: "embed", exported: true, lines: 25 },
      { name: "_load_model", exported: false, lines: 30 },
    ],
    types: [{ name: "HuggingFaceConfig", kind: "class" }],
    classes: [{ name: "HuggingFaceEmbedding" }],
    imports: ["mem0/embeddings/base.py", "mem0/embeddings/configs.py"],
    importedBy: ["mem0/utils/factory.py"],
    complexity: 10,
    isReactComponent: false,
    hasUnusedExports: false,
    position: { x: 5.6, z: -5.2 },
    district: "embeddings",
  },
  {
    path: "mem0/embeddings/base.py",
    lines: 90,
    functions: [
      { name: "BaseEmbedding", exported: true, lines: 30 },
      { name: "embed", exported: true, lines: 15 },
    ],
    types: [{ name: "BaseEmbedding", kind: "class" }],
    classes: [{ name: "BaseEmbedding" }],
    imports: ["mem0/configs/base.py"],
    importedBy: [
      "mem0/embeddings/openai.py",
      "mem0/embeddings/huggingface.py",
      "mem0/memory/main.py",
    ],
    complexity: 5,
    isReactComponent: false,
    hasUnusedExports: false,
    position: { x: 3.8, z: -3.4 },
    district: "embeddings",
  },
  {
    path: "mem0/embeddings/configs.py",
    lines: 70,
    functions: [
      { name: "EmbedderConfig", exported: true, lines: 25 },
      { name: "get_default_config", exported: true, lines: 15 },
    ],
    types: [
      { name: "EmbedderConfig", kind: "class" },
      { name: "EmbedderProvider", kind: "enum" },
    ],
    classes: [{ name: "EmbedderConfig" }],
    imports: ["mem0/configs/base.py"],
    importedBy: ["mem0/embeddings/openai.py", "mem0/embeddings/huggingface.py"],
    complexity: 3,
    isReactComponent: false,
    hasUnusedExports: false,
    position: { x: 5.6, z: -3.4 },
    district: "embeddings",
  },

  // ── vector_stores district ──
  {
    path: "mem0/vector_stores/qdrant.py",
    lines: 260,
    functions: [
      { name: "Qdrant", exported: true, lines: 60 },
      { name: "insert", exported: true, lines: 40 },
      { name: "search", exported: true, lines: 45 },
      { name: "delete", exported: true, lines: 20 },
      { name: "update", exported: true, lines: 30 },
      { name: "_create_collection", exported: false, lines: 25 },
    ],
    types: [{ name: "QdrantConfig", kind: "class" }],
    classes: [{ name: "Qdrant" }],
    imports: ["mem0/vector_stores/base.py", "mem0/vector_stores/configs.py", "mem0/utils/logger.py"],
    importedBy: ["mem0/utils/factory.py"],
    complexity: 20,
    isReactComponent: false,
    hasUnusedExports: false,
    position: { x: 9.8, z: -5.2 },
    district: "vector_stores",
  },
  {
    path: "mem0/vector_stores/chroma.py",
    lines: 210,
    functions: [
      { name: "ChromaDB", exported: true, lines: 50 },
      { name: "insert", exported: true, lines: 35 },
      { name: "search", exported: true, lines: 40 },
      { name: "delete", exported: true, lines: 18 },
      { name: "update", exported: true, lines: 25 },
    ],
    types: [{ name: "ChromaConfig", kind: "class" }],
    classes: [{ name: "ChromaDB" }],
    imports: ["mem0/vector_stores/base.py", "mem0/vector_stores/configs.py"],
    importedBy: ["mem0/utils/factory.py"],
    complexity: 17,
    isReactComponent: false,
    hasUnusedExports: false,
    position: { x: 11.6, z: -5.2 },
    district: "vector_stores",
  },
  {
    path: "mem0/vector_stores/base.py",
    lines: 110,
    functions: [
      { name: "VectorStoreBase", exported: true, lines: 35 },
      { name: "insert", exported: true, lines: 15 },
      { name: "search", exported: true, lines: 15 },
      { name: "delete", exported: true, lines: 10 },
    ],
    types: [
      { name: "VectorStoreBase", kind: "class" },
      { name: "SearchResult", kind: "class" },
    ],
    classes: [{ name: "VectorStoreBase" }],
    imports: ["mem0/configs/base.py"],
    importedBy: [
      "mem0/vector_stores/qdrant.py",
      "mem0/vector_stores/chroma.py",
      "mem0/memory/main.py",
    ],
    complexity: 6,
    isReactComponent: false,
    hasUnusedExports: false,
    position: { x: 9.8, z: -3.4 },
    district: "vector_stores",
  },
  {
    path: "mem0/vector_stores/configs.py",
    lines: 75,
    functions: [
      { name: "VectorStoreConfig", exported: true, lines: 25 },
      { name: "get_default_config", exported: true, lines: 15 },
    ],
    types: [
      { name: "VectorStoreConfig", kind: "class" },
      { name: "VectorStoreProvider", kind: "enum" },
    ],
    classes: [{ name: "VectorStoreConfig" }],
    imports: ["mem0/configs/base.py"],
    importedBy: ["mem0/vector_stores/qdrant.py", "mem0/vector_stores/chroma.py"],
    complexity: 3,
    isReactComponent: false,
    hasUnusedExports: false,
    position: { x: 11.6, z: -3.4 },
    district: "vector_stores",
  },

  // ── graphs district (knowledge graphs) ──
  {
    path: "mem0/graphs/tools.py",
    lines: 240,
    functions: [
      { name: "extract_entities", exported: true, lines: 60 },
      { name: "build_relations", exported: true, lines: 50 },
      { name: "search_graph", exported: true, lines: 45 },
      { name: "_parse_neo4j_result", exported: false, lines: 30 },
      { name: "_format_cypher", exported: false, lines: 25 },
    ],
    types: [
      { name: "Entity", kind: "class" },
      { name: "Relation", kind: "class" },
    ],
    classes: [],
    imports: ["mem0/graphs/base.py", "mem0/graphs/utils.py", "mem0/utils/logger.py"],
    importedBy: ["mem0/memory/main.py"],
    complexity: 22,
    isReactComponent: false,
    hasUnusedExports: false,
    position: { x: -8.2, z: -0.7 },
    district: "graphs",
  },
  {
    path: "mem0/graphs/utils.py",
    lines: 140,
    functions: [
      { name: "get_update_memory_messages", exported: true, lines: 35 },
      { name: "get_delete_messages", exported: true, lines: 25 },
      { name: "format_entities", exported: true, lines: 20 },
      { name: "parse_graph_response", exported: true, lines: 30 },
    ],
    types: [],
    classes: [],
    imports: ["mem0/memory/utils.py", "mem0/configs/prompts.py"],
    importedBy: ["mem0/graphs/tools.py"],
    complexity: 10,
    isReactComponent: false,
    hasUnusedExports: true,
    position: { x: -6.4, z: -0.7 },
    district: "graphs",
  },
  {
    path: "mem0/graphs/base.py",
    lines: 110,
    functions: [
      { name: "MemoryGraph", exported: true, lines: 40 },
      { name: "add", exported: true, lines: 20 },
      { name: "search", exported: true, lines: 20 },
    ],
    types: [{ name: "MemoryGraph", kind: "class" }],
    classes: [{ name: "MemoryGraph" }],
    imports: ["mem0/llms/base.py", "mem0/configs/base.py"],
    importedBy: ["mem0/graphs/tools.py"],
    complexity: 9,
    isReactComponent: false,
    hasUnusedExports: false,
    position: { x: -4.6, z: -0.7 },
    district: "graphs",
  },

  // ── client district (SDK) ──
  {
    path: "mem0/client/main.py",
    lines: 350,
    functions: [
      { name: "MemoryClient", exported: true, lines: 80 },
      { name: "add", exported: true, lines: 40 },
      { name: "search", exported: true, lines: 35 },
      { name: "get_all", exported: true, lines: 25 },
      { name: "delete", exported: true, lines: 20 },
      { name: "reset", exported: true, lines: 15 },
      { name: "_make_request", exported: false, lines: 45 },
    ],
    types: [{ name: "MemoryClient", kind: "class" }],
    classes: [{ name: "MemoryClient" }],
    imports: [
      "mem0/client/models.py",
      "mem0/client/api.py",
      "mem0/memory/main.py",
      "mem0/utils/logger.py",
    ],
    importedBy: [],
    complexity: 19,
    isReactComponent: false,
    hasUnusedExports: false,
    position: { x: -2.2, z: -0.7 },
    district: "client",
  },
  {
    path: "mem0/client/models.py",
    lines: 120,
    functions: [
      { name: "MemoryModel", exported: true, lines: 25 },
      { name: "SearchResult", exported: true, lines: 20 },
      { name: "MemoryHistory", exported: true, lines: 15 },
      { name: "APIResponse", exported: true, lines: 20 },
    ],
    types: [
      { name: "MemoryModel", kind: "class" },
      { name: "SearchResult", kind: "class" },
      { name: "APIResponse", kind: "class" },
    ],
    classes: [{ name: "MemoryModel" }, { name: "SearchResult" }, { name: "APIResponse" }],
    imports: [],
    importedBy: ["mem0/client/main.py", "mem0/client/api.py"],
    complexity: 5,
    isReactComponent: false,
    hasUnusedExports: false,
    position: { x: -0.4, z: -0.7 },
    district: "client",
  },
  {
    path: "mem0/client/api.py",
    lines: 180,
    functions: [
      { name: "APIClient", exported: true, lines: 50 },
      { name: "get", exported: true, lines: 25 },
      { name: "post", exported: true, lines: 30 },
      { name: "delete", exported: true, lines: 20 },
      { name: "_handle_response", exported: false, lines: 25 },
    ],
    types: [{ name: "APIClient", kind: "class" }],
    classes: [{ name: "APIClient" }],
    imports: ["mem0/client/models.py", "mem0/utils/logger.py"],
    importedBy: ["mem0/client/main.py"],
    complexity: 13,
    isReactComponent: false,
    hasUnusedExports: false,
    position: { x: 1.4, z: -0.7 },
    district: "client",
  },

  // ── configs district ──
  {
    path: "mem0/configs/base.py",
    lines: 200,
    functions: [
      { name: "MemoryConfig", exported: true, lines: 50 },
      { name: "AzureConfig", exported: true, lines: 25 },
      { name: "validate_config", exported: true, lines: 35 },
      { name: "merge_configs", exported: true, lines: 25 },
      { name: "_resolve_provider", exported: false, lines: 30 },
    ],
    types: [
      { name: "MemoryConfig", kind: "class" },
      { name: "AzureConfig", kind: "class" },
      { name: "ConfigVersion", kind: "enum" },
    ],
    classes: [{ name: "MemoryConfig" }, { name: "AzureConfig" }],
    imports: [],
    importedBy: [
      "mem0/memory/main.py",
      "mem0/memory/base.py",
      "mem0/llms/base.py",
      "mem0/llms/configs.py",
      "mem0/embeddings/base.py",
      "mem0/embeddings/configs.py",
      "mem0/vector_stores/base.py",
      "mem0/vector_stores/configs.py",
      "mem0/graphs/base.py",
    ],
    complexity: 15,
    isReactComponent: false,
    hasUnusedExports: false,
    position: { x: 3.8, z: -0.7 },
    district: "configs",
  },
  {
    path: "mem0/configs/prompts.py",
    lines: 140,
    functions: [
      { name: "MEMORY_DEDUCTION_PROMPT", exported: true, lines: 15 },
      { name: "UPDATE_MEMORY_PROMPT", exported: true, lines: 15 },
      { name: "DELETE_MEMORY_PROMPT", exported: true, lines: 10 },
      { name: "GRAPH_EXTRACTION_PROMPT", exported: true, lines: 20 },
      { name: "get_system_prompt", exported: true, lines: 25 },
    ],
    types: [],
    classes: [],
    imports: [],
    importedBy: ["mem0/memory/utils.py", "mem0/graphs/utils.py"],
    complexity: 4,
    isReactComponent: false,
    hasUnusedExports: true,
    position: { x: 5.6, z: -0.7 },
    district: "configs",
  },
  {
    path: "mem0/configs/defaults.py",
    lines: 90,
    functions: [
      { name: "DEFAULT_LLM_CONFIG", exported: true, lines: 15 },
      { name: "DEFAULT_EMBEDDER_CONFIG", exported: true, lines: 15 },
      { name: "DEFAULT_VECTOR_STORE_CONFIG", exported: true, lines: 15 },
      { name: "get_defaults", exported: true, lines: 20 },
    ],
    types: [],
    classes: [],
    imports: [],
    importedBy: ["mem0/memory/setup.py", "mem0/utils/factory.py"],
    complexity: 3,
    isReactComponent: false,
    hasUnusedExports: false,
    position: { x: 7.4, z: -0.7 },
    district: "configs",
  },

  // ── utils district ──
  {
    path: "mem0/utils/factory.py",
    lines: 230,
    functions: [
      { name: "LLMFactory", exported: true, lines: 50 },
      { name: "EmbedderFactory", exported: true, lines: 45 },
      { name: "VectorStoreFactory", exported: true, lines: 45 },
      { name: "GraphFactory", exported: true, lines: 35 },
      { name: "_resolve_provider", exported: false, lines: 25 },
    ],
    types: [{ name: "ProviderRegistry", kind: "class" }],
    classes: [{ name: "LLMFactory" }, { name: "EmbedderFactory" }],
    imports: [
      "mem0/llms/openai.py",
      "mem0/llms/anthropic.py",
      "mem0/llms/azure_openai.py",
      "mem0/embeddings/openai.py",
      "mem0/embeddings/huggingface.py",
      "mem0/vector_stores/qdrant.py",
      "mem0/vector_stores/chroma.py",
      "mem0/configs/defaults.py",
    ],
    importedBy: ["mem0/memory/main.py"],
    complexity: 18,
    isReactComponent: false,
    hasUnusedExports: false,
    position: { x: 9.8, z: -0.7 },
    district: "utils",
  },
  {
    path: "mem0/utils/logger.py",
    lines: 75,
    functions: [
      { name: "get_logger", exported: true, lines: 25 },
      { name: "setup_logging", exported: true, lines: 20 },
      { name: "format_log", exported: false, lines: 15 },
    ],
    types: [{ name: "LogLevel", kind: "enum" }],
    classes: [],
    imports: [],
    importedBy: [
      "mem0/memory/base.py",
      "mem0/memory/telemetry.py",
      "mem0/llms/openai.py",
      "mem0/llms/anthropic.py",
      "mem0/embeddings/openai.py",
      "mem0/vector_stores/qdrant.py",
      "mem0/graphs/tools.py",
      "mem0/client/main.py",
      "mem0/client/api.py",
    ],
    complexity: 4,
    isReactComponent: false,
    hasUnusedExports: false,
    position: { x: 11.6, z: -0.7 },
    district: "utils",
  },
  {
    path: "mem0/utils/helpers.py",
    lines: 95,
    functions: [
      { name: "generate_uuid", exported: true, lines: 10 },
      { name: "chunk_list", exported: true, lines: 15 },
      { name: "retry_with_backoff", exported: true, lines: 30 },
      { name: "flatten_dict", exported: true, lines: 20 },
    ],
    types: [],
    classes: [],
    imports: [],
    importedBy: ["mem0/utils/factory.py", "mem0/memory/main.py"],
    complexity: 7,
    isReactComponent: false,
    hasUnusedExports: true,
    position: { x: 13.4, z: -0.7 },
    district: "utils",
  },
]

// Add default values for new fields
const files: FileData[] = filesRaw.map((f) => ({
  ...f,
  externalImports: [] as string[],
  decorators: [] as string[],
  fileType: "python" as FileData["fileType"],
}))

// ---------- computed stats ----------

const stats: CityStats = {
  totalFiles: files.length,
  totalFunctions: files.reduce((sum, f) => sum + f.functions.length, 0),
  totalLines: files.reduce((sum, f) => sum + f.lines, 0),
  totalTypes: files.reduce((sum, f) => sum + f.types.length, 0),
  totalImports: files.reduce((sum, f) => sum + f.imports.length, 0),
  unusedExports: files.filter((f) => f.hasUnusedExports).length,
}

// ---------- export ----------

export const SAMPLE_CITY_DATA: CitySnapshot = {
  files,
  districts,
  stats,
}
