import type { CitySnapshot, FileData, DistrictData, CityStats } from "./types/city"
import { DISTRICT_COLORS } from "./types/city"

// ---------- districts ----------

const districts: DistrictData[] = [
  {
    name: "src",
    color: DISTRICT_COLORS[0], // cyan
    files: [
      "src/App.tsx",
      "src/main.tsx",
      "src/router.tsx",
      "src/config.ts",
      "src/constants.ts",
      "src/vite-env.d.ts",
    ],
    bounds: { x: -12, z: -12, width: 12, depth: 12 },
  },
  {
    name: "components",
    color: DISTRICT_COLORS[1], // green
    files: [
      "src/components/Button.tsx",
      "src/components/Modal.tsx",
      "src/components/Sidebar.tsx",
      "src/components/Header.tsx",
      "src/components/Avatar.tsx",
      "src/components/Toast.tsx",
      "src/components/DataTable.tsx",
      "src/components/FormField.tsx",
    ],
    bounds: { x: 2, z: -12, width: 14, depth: 12 },
  },
  {
    name: "hooks",
    color: DISTRICT_COLORS[4], // purple
    files: [
      "src/hooks/useAuth.ts",
      "src/hooks/useFetch.ts",
      "src/hooks/useLocalStorage.ts",
      "src/hooks/useDebounce.ts",
      "src/hooks/useMediaQuery.ts",
    ],
    bounds: { x: -12, z: 2, width: 10, depth: 10 },
  },
  {
    name: "utils",
    color: DISTRICT_COLORS[3], // amber
    files: [
      "src/utils/format.ts",
      "src/utils/validate.ts",
      "src/utils/cn.ts",
      "src/utils/date.ts",
      "src/utils/logger.ts",
    ],
    bounds: { x: 0, z: 2, width: 8, depth: 10 },
  },
  {
    name: "api",
    color: DISTRICT_COLORS[2], // blue
    files: [
      "src/api/client.ts",
      "src/api/auth.ts",
      "src/api/users.ts",
      "src/api/projects.ts",
      "src/api/middleware.ts",
      "src/api/types.ts",
    ],
    bounds: { x: 10, z: 2, width: 10, depth: 10 },
  },
]

// ---------- files ----------

const files: FileData[] = [
  // ── src district ──
  {
    path: "src/App.tsx",
    lines: 320,
    functions: [
      { name: "App", exported: true, lines: 180 },
      { name: "AppProviders", exported: true, lines: 60 },
      { name: "ErrorBoundary", exported: true, lines: 50 },
    ],
    types: [{ name: "AppProps", kind: "interface" }],
    classes: [],
    imports: [
      "src/router.tsx",
      "src/hooks/useAuth.ts",
      "src/components/Header.tsx",
      "src/components/Sidebar.tsx",
      "src/components/Toast.tsx",
    ],
    importedBy: ["src/main.tsx"],
    complexity: 18,
    isReactComponent: true,
    hasUnusedExports: false,
    position: { x: -10, z: -10 },
    district: "src",
  },
  {
    path: "src/main.tsx",
    lines: 30,
    functions: [{ name: "main", exported: false, lines: 20 }],
    types: [],
    classes: [],
    imports: ["src/App.tsx"],
    importedBy: [],
    complexity: 2,
    isReactComponent: false,
    hasUnusedExports: false,
    position: { x: -7, z: -10 },
    district: "src",
  },
  {
    path: "src/router.tsx",
    lines: 180,
    functions: [
      { name: "createRouter", exported: true, lines: 90 },
      { name: "ProtectedRoute", exported: true, lines: 40 },
    ],
    types: [{ name: "RouteConfig", kind: "type" }],
    classes: [],
    imports: ["src/hooks/useAuth.ts", "src/components/Sidebar.tsx"],
    importedBy: ["src/App.tsx"],
    complexity: 14,
    isReactComponent: true,
    hasUnusedExports: false,
    position: { x: -4, z: -10 },
    district: "src",
  },
  {
    path: "src/config.ts",
    lines: 55,
    functions: [
      { name: "getConfig", exported: true, lines: 30 },
      { name: "validateEnv", exported: true, lines: 15 },
    ],
    types: [
      { name: "Config", kind: "interface" },
      { name: "Environment", kind: "enum" },
    ],
    classes: [],
    imports: [],
    importedBy: ["src/api/client.ts", "src/api/middleware.ts"],
    complexity: 5,
    isReactComponent: false,
    hasUnusedExports: true,
    position: { x: -10, z: -7 },
    district: "src",
  },
  {
    path: "src/constants.ts",
    lines: 40,
    functions: [],
    types: [{ name: "Theme", kind: "enum" }],
    classes: [],
    imports: [],
    importedBy: ["src/App.tsx", "src/components/Header.tsx"],
    complexity: 1,
    isReactComponent: false,
    hasUnusedExports: true,
    position: { x: -7, z: -7 },
    district: "src",
  },
  {
    path: "src/vite-env.d.ts",
    lines: 20,
    functions: [],
    types: [],
    classes: [],
    imports: [],
    importedBy: [],
    complexity: 1,
    isReactComponent: false,
    hasUnusedExports: false,
    position: { x: -4, z: -7 },
    district: "src",
  },

  // ── components district ──
  {
    path: "src/components/Button.tsx",
    lines: 95,
    functions: [
      { name: "Button", exported: true, lines: 55 },
      { name: "IconButton", exported: true, lines: 30 },
    ],
    types: [
      { name: "ButtonProps", kind: "interface" },
      { name: "ButtonVariant", kind: "type" },
    ],
    classes: [],
    imports: ["src/utils/cn.ts"],
    importedBy: [
      "src/components/Modal.tsx",
      "src/components/Header.tsx",
      "src/components/FormField.tsx",
    ],
    complexity: 6,
    isReactComponent: true,
    hasUnusedExports: false,
    position: { x: 4, z: -10 },
    district: "components",
  },
  {
    path: "src/components/Modal.tsx",
    lines: 150,
    functions: [
      { name: "Modal", exported: true, lines: 80 },
      { name: "ModalHeader", exported: true, lines: 20 },
      { name: "ModalFooter", exported: true, lines: 20 },
      { name: "useModalState", exported: false, lines: 15 },
    ],
    types: [{ name: "ModalProps", kind: "interface" }],
    classes: [],
    imports: ["src/components/Button.tsx", "src/utils/cn.ts"],
    importedBy: ["src/components/DataTable.tsx"],
    complexity: 12,
    isReactComponent: true,
    hasUnusedExports: true,
    position: { x: 7, z: -10 },
    district: "components",
  },
  {
    path: "src/components/Sidebar.tsx",
    lines: 210,
    functions: [
      { name: "Sidebar", exported: true, lines: 100 },
      { name: "SidebarItem", exported: true, lines: 40 },
      { name: "SidebarGroup", exported: true, lines: 35 },
    ],
    types: [
      { name: "SidebarProps", kind: "interface" },
      { name: "NavItem", kind: "type" },
    ],
    classes: [],
    imports: [
      "src/utils/cn.ts",
      "src/hooks/useMediaQuery.ts",
      "src/hooks/useAuth.ts",
    ],
    importedBy: ["src/App.tsx", "src/router.tsx"],
    complexity: 15,
    isReactComponent: true,
    hasUnusedExports: false,
    position: { x: 10, z: -10 },
    district: "components",
  },
  {
    path: "src/components/Header.tsx",
    lines: 170,
    functions: [
      { name: "Header", exported: true, lines: 80 },
      { name: "SearchBar", exported: false, lines: 45 },
      { name: "UserMenu", exported: false, lines: 35 },
    ],
    types: [{ name: "HeaderProps", kind: "interface" }],
    classes: [],
    imports: [
      "src/components/Button.tsx",
      "src/components/Avatar.tsx",
      "src/hooks/useAuth.ts",
      "src/utils/cn.ts",
    ],
    importedBy: ["src/App.tsx"],
    complexity: 11,
    isReactComponent: true,
    hasUnusedExports: false,
    position: { x: 13, z: -10 },
    district: "components",
  },
  {
    path: "src/components/Avatar.tsx",
    lines: 60,
    functions: [{ name: "Avatar", exported: true, lines: 40 }],
    types: [
      { name: "AvatarProps", kind: "interface" },
      { name: "AvatarSize", kind: "type" },
    ],
    classes: [],
    imports: ["src/utils/cn.ts"],
    importedBy: ["src/components/Header.tsx"],
    complexity: 4,
    isReactComponent: true,
    hasUnusedExports: false,
    position: { x: 4, z: -7 },
    district: "components",
  },
  {
    path: "src/components/Toast.tsx",
    lines: 120,
    functions: [
      { name: "Toast", exported: true, lines: 50 },
      { name: "ToastContainer", exported: true, lines: 30 },
      { name: "useToast", exported: true, lines: 25 },
    ],
    types: [
      { name: "ToastProps", kind: "interface" },
      { name: "ToastType", kind: "enum" },
    ],
    classes: [],
    imports: ["src/utils/cn.ts"],
    importedBy: ["src/App.tsx"],
    complexity: 8,
    isReactComponent: true,
    hasUnusedExports: true,
    position: { x: 7, z: -7 },
    district: "components",
  },
  {
    path: "src/components/DataTable.tsx",
    lines: 480,
    functions: [
      { name: "DataTable", exported: true, lines: 150 },
      { name: "TableHeader", exported: false, lines: 60 },
      { name: "TableRow", exported: false, lines: 45 },
      { name: "TablePagination", exported: true, lines: 55 },
      { name: "useSorting", exported: false, lines: 40 },
      { name: "useFiltering", exported: false, lines: 35 },
      { name: "useSelection", exported: false, lines: 30 },
      { name: "formatCell", exported: false, lines: 25 },
    ],
    types: [
      { name: "DataTableProps", kind: "interface" },
      { name: "Column", kind: "interface" },
      { name: "SortDirection", kind: "enum" },
    ],
    classes: [],
    imports: [
      "src/components/Button.tsx",
      "src/components/Modal.tsx",
      "src/utils/format.ts",
      "src/utils/cn.ts",
    ],
    importedBy: [],
    complexity: 28,
    isReactComponent: true,
    hasUnusedExports: false,
    position: { x: 10, z: -7 },
    district: "components",
  },
  {
    path: "src/components/FormField.tsx",
    lines: 200,
    functions: [
      { name: "FormField", exported: true, lines: 70 },
      { name: "TextInput", exported: true, lines: 35 },
      { name: "SelectInput", exported: true, lines: 40 },
      { name: "CheckboxInput", exported: true, lines: 25 },
      { name: "useFieldValidation", exported: false, lines: 20 },
    ],
    types: [
      { name: "FormFieldProps", kind: "interface" },
      { name: "ValidationRule", kind: "type" },
    ],
    classes: [],
    imports: [
      "src/components/Button.tsx",
      "src/utils/validate.ts",
      "src/utils/cn.ts",
    ],
    importedBy: [],
    complexity: 16,
    isReactComponent: true,
    hasUnusedExports: true,
    position: { x: 13, z: -7 },
    district: "components",
  },

  // ── hooks district ──
  {
    path: "src/hooks/useAuth.ts",
    lines: 180,
    functions: [
      { name: "useAuth", exported: true, lines: 90 },
      { name: "AuthProvider", exported: true, lines: 50 },
      { name: "usePermissions", exported: true, lines: 30 },
    ],
    types: [
      { name: "AuthState", kind: "interface" },
      { name: "User", kind: "interface" },
      { name: "Permission", kind: "enum" },
    ],
    classes: [],
    imports: ["src/api/auth.ts", "src/utils/logger.ts"],
    importedBy: [
      "src/App.tsx",
      "src/router.tsx",
      "src/components/Sidebar.tsx",
      "src/components/Header.tsx",
    ],
    complexity: 22,
    isReactComponent: false,
    hasUnusedExports: false,
    position: { x: -10, z: 4 },
    district: "hooks",
  },
  {
    path: "src/hooks/useFetch.ts",
    lines: 140,
    functions: [
      { name: "useFetch", exported: true, lines: 70 },
      { name: "useMutation", exported: true, lines: 50 },
    ],
    types: [
      { name: "FetchState", kind: "interface" },
      { name: "FetchOptions", kind: "type" },
    ],
    classes: [],
    imports: ["src/api/client.ts"],
    importedBy: ["src/api/users.ts", "src/api/projects.ts"],
    complexity: 15,
    isReactComponent: false,
    hasUnusedExports: false,
    position: { x: -7, z: 4 },
    district: "hooks",
  },
  {
    path: "src/hooks/useLocalStorage.ts",
    lines: 65,
    functions: [{ name: "useLocalStorage", exported: true, lines: 45 }],
    types: [],
    classes: [],
    imports: [],
    importedBy: ["src/hooks/useAuth.ts"],
    complexity: 7,
    isReactComponent: false,
    hasUnusedExports: false,
    position: { x: -10, z: 7 },
    district: "hooks",
  },
  {
    path: "src/hooks/useDebounce.ts",
    lines: 35,
    functions: [{ name: "useDebounce", exported: true, lines: 25 }],
    types: [],
    classes: [],
    imports: [],
    importedBy: ["src/components/Header.tsx"],
    complexity: 3,
    isReactComponent: false,
    hasUnusedExports: false,
    position: { x: -7, z: 7 },
    district: "hooks",
  },
  {
    path: "src/hooks/useMediaQuery.ts",
    lines: 45,
    functions: [{ name: "useMediaQuery", exported: true, lines: 35 }],
    types: [],
    classes: [],
    imports: [],
    importedBy: ["src/components/Sidebar.tsx"],
    complexity: 4,
    isReactComponent: false,
    hasUnusedExports: false,
    position: { x: -4, z: 4 },
    district: "hooks",
  },

  // ── utils district ──
  {
    path: "src/utils/format.ts",
    lines: 110,
    functions: [
      { name: "formatCurrency", exported: true, lines: 20 },
      { name: "formatDate", exported: true, lines: 25 },
      { name: "formatNumber", exported: true, lines: 15 },
      { name: "formatFileSize", exported: true, lines: 18 },
      { name: "truncate", exported: true, lines: 10 },
    ],
    types: [{ name: "FormatOptions", kind: "type" }],
    classes: [],
    imports: ["src/utils/date.ts"],
    importedBy: ["src/components/DataTable.tsx"],
    complexity: 8,
    isReactComponent: false,
    hasUnusedExports: true,
    position: { x: 2, z: 4 },
    district: "utils",
  },
  {
    path: "src/utils/validate.ts",
    lines: 130,
    functions: [
      { name: "validateEmail", exported: true, lines: 15 },
      { name: "validatePassword", exported: true, lines: 20 },
      { name: "validateUrl", exported: true, lines: 12 },
      { name: "validatePhone", exported: true, lines: 10 },
      { name: "composeValidators", exported: true, lines: 25 },
      { name: "createValidator", exported: true, lines: 30 },
    ],
    types: [
      { name: "Validator", kind: "type" },
      { name: "ValidationResult", kind: "interface" },
    ],
    classes: [],
    imports: [],
    importedBy: [
      "src/components/FormField.tsx",
      "src/api/auth.ts",
    ],
    complexity: 12,
    isReactComponent: false,
    hasUnusedExports: true,
    position: { x: 5, z: 4 },
    district: "utils",
  },
  {
    path: "src/utils/cn.ts",
    lines: 20,
    functions: [{ name: "cn", exported: true, lines: 10 }],
    types: [],
    classes: [],
    imports: [],
    importedBy: [
      "src/components/Button.tsx",
      "src/components/Modal.tsx",
      "src/components/Sidebar.tsx",
      "src/components/Header.tsx",
      "src/components/Avatar.tsx",
      "src/components/Toast.tsx",
      "src/components/DataTable.tsx",
      "src/components/FormField.tsx",
    ],
    complexity: 1,
    isReactComponent: false,
    hasUnusedExports: false,
    position: { x: 2, z: 7 },
    district: "utils",
  },
  {
    path: "src/utils/date.ts",
    lines: 85,
    functions: [
      { name: "parseDate", exported: true, lines: 20 },
      { name: "diffDays", exported: true, lines: 12 },
      { name: "isWeekend", exported: true, lines: 8 },
      { name: "startOfWeek", exported: true, lines: 15 },
    ],
    types: [],
    classes: [],
    imports: [],
    importedBy: ["src/utils/format.ts"],
    complexity: 6,
    isReactComponent: false,
    hasUnusedExports: true,
    position: { x: 5, z: 7 },
    district: "utils",
  },
  {
    path: "src/utils/logger.ts",
    lines: 70,
    functions: [
      { name: "createLogger", exported: true, lines: 35 },
      { name: "formatLogEntry", exported: false, lines: 20 },
    ],
    types: [
      { name: "LogLevel", kind: "enum" },
      { name: "LogEntry", kind: "interface" },
    ],
    classes: [],
    imports: [],
    importedBy: ["src/hooks/useAuth.ts", "src/api/middleware.ts"],
    complexity: 5,
    isReactComponent: false,
    hasUnusedExports: false,
    position: { x: 2, z: 10 },
    district: "utils",
  },

  // ── api district ──
  {
    path: "src/api/client.ts",
    lines: 200,
    functions: [
      { name: "createClient", exported: true, lines: 60 },
      { name: "handleResponse", exported: false, lines: 35 },
      { name: "retryRequest", exported: false, lines: 40 },
      { name: "buildUrl", exported: false, lines: 20 },
      { name: "serializeParams", exported: true, lines: 15 },
    ],
    types: [
      { name: "ClientConfig", kind: "interface" },
      { name: "RequestOptions", kind: "type" },
    ],
    classes: [],
    imports: ["src/config.ts", "src/api/middleware.ts", "src/api/types.ts"],
    importedBy: [
      "src/hooks/useFetch.ts",
      "src/api/auth.ts",
      "src/api/users.ts",
      "src/api/projects.ts",
    ],
    complexity: 21,
    isReactComponent: false,
    hasUnusedExports: false,
    position: { x: 12, z: 4 },
    district: "api",
  },
  {
    path: "src/api/auth.ts",
    lines: 160,
    functions: [
      { name: "login", exported: true, lines: 40 },
      { name: "logout", exported: true, lines: 15 },
      { name: "refreshToken", exported: true, lines: 35 },
      { name: "register", exported: true, lines: 45 },
    ],
    types: [
      { name: "LoginPayload", kind: "interface" },
      { name: "AuthTokens", kind: "interface" },
    ],
    classes: [],
    imports: [
      "src/api/client.ts",
      "src/api/types.ts",
      "src/utils/validate.ts",
    ],
    importedBy: ["src/hooks/useAuth.ts"],
    complexity: 14,
    isReactComponent: false,
    hasUnusedExports: false,
    position: { x: 15, z: 4 },
    district: "api",
  },
  {
    path: "src/api/users.ts",
    lines: 120,
    functions: [
      { name: "getUsers", exported: true, lines: 25 },
      { name: "getUser", exported: true, lines: 20 },
      { name: "updateUser", exported: true, lines: 30 },
      { name: "deleteUser", exported: true, lines: 15 },
    ],
    types: [{ name: "UserFilters", kind: "interface" }],
    classes: [],
    imports: ["src/api/client.ts", "src/api/types.ts"],
    importedBy: [],
    complexity: 8,
    isReactComponent: false,
    hasUnusedExports: false,
    position: { x: 18, z: 4 },
    district: "api",
  },
  {
    path: "src/api/projects.ts",
    lines: 190,
    functions: [
      { name: "getProjects", exported: true, lines: 30 },
      { name: "getProject", exported: true, lines: 25 },
      { name: "createProject", exported: true, lines: 40 },
      { name: "updateProject", exported: true, lines: 35 },
      { name: "deleteProject", exported: true, lines: 15 },
      { name: "archiveProject", exported: true, lines: 20 },
    ],
    types: [
      { name: "ProjectFilters", kind: "interface" },
      { name: "ProjectStatus", kind: "enum" },
    ],
    classes: [],
    imports: ["src/api/client.ts", "src/api/types.ts"],
    importedBy: [],
    complexity: 10,
    isReactComponent: false,
    hasUnusedExports: false,
    position: { x: 12, z: 7 },
    district: "api",
  },
  {
    path: "src/api/middleware.ts",
    lines: 140,
    functions: [
      { name: "authMiddleware", exported: true, lines: 40 },
      { name: "loggingMiddleware", exported: true, lines: 30 },
      { name: "retryMiddleware", exported: true, lines: 45 },
    ],
    types: [
      { name: "Middleware", kind: "type" },
      { name: "MiddlewareContext", kind: "interface" },
    ],
    classes: [],
    imports: ["src/config.ts", "src/utils/logger.ts"],
    importedBy: ["src/api/client.ts"],
    complexity: 16,
    isReactComponent: false,
    hasUnusedExports: false,
    position: { x: 15, z: 7 },
    district: "api",
  },
  {
    path: "src/api/types.ts",
    lines: 90,
    functions: [],
    types: [
      { name: "ApiResponse", kind: "interface" },
      { name: "PaginatedResponse", kind: "interface" },
      { name: "ApiError", kind: "interface" },
      { name: "HttpMethod", kind: "type" },
      { name: "StatusCode", kind: "enum" },
    ],
    classes: [],
    imports: [],
    importedBy: [
      "src/api/client.ts",
      "src/api/auth.ts",
      "src/api/users.ts",
      "src/api/projects.ts",
    ],
    complexity: 1,
    isReactComponent: false,
    hasUnusedExports: false,
    position: { x: 18, z: 7 },
    district: "api",
  },
]

// ---------- computed stats ----------

const stats: CityStats = {
  totalFiles: files.length,
  totalFunctions: files.reduce((sum, f) => sum + f.functions.length, 0),
  totalLines: files.reduce((sum, f) => sum + f.lines, 0),
  totalTypes: files.reduce((sum, f) => sum + f.types.length, 0),
  totalImports: files.reduce((sum, f) => sum + f.imports.length, 0),
  unusedExports: files.filter((f) => f.hasUnusedExports).length,
}

// ---------- export ----------

export const SAMPLE_CITY_DATA: CitySnapshot = {
  files,
  districts,
  stats,
}
